### ISSUE TITLE
Compiled CSS filename in settings defaults to styles instead of styles.css

### ISSUE THREAD

**Issue by mc72** [lesaff/ProcessWire-Sassify#5]
When upgrading or installing the field for the _"Compiled CSS Filename"_ defaults to `styles` instead of `styles.css`.  This results in the output of `<link rel="stylesheet" type="text/css" href="/site/templates/css/styles">`

**Comment by webworkerJoshua** [comment]
Solved in [Pull request 8](https://github.com/lesaff/ProcessWire-Sassify/pull/8).
